config/routes.rb
Rails.application.routes.draw do
  get 'home/index'
  get 'home/about'
  get 'projects/archive'
  devise_for :users, :controllers => { :registrations => "registrations", :omniauth_callbacks => "users/omniauth_callbacks" }
  resources :projects, shallow: true do
    member do
        get :calendar
      end
    resources :goals do
      member do
        get :calendar
        get :list
      end
    end
    resources :entries
  end

  resources :users, only: [:show, :edit, :update] do 
    member do
      get :settings
      get :profile
    end
    devise_scope :user do
      get 'sign_out', :to => 'devise/sessions#destroy', :as => :destroy_user_session
    end
  end
  
 
  

  root 'home#index'

end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  	devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable, :confirmable,
         :omniauthable,  :omniauth_providers => [:twitter]
	has_many :projects, :dependent => :destroy
	has_many :entries, through: :projects, :dependent => :destroy
	has_many :goals, through: :projects, :dependent => :destroy
	acts_as_taggable
	has_attached_file :avatar, :styles => { :medium => "300x300>", :thumb => "100x100>" }, :storage => :s3, :s3_credentials => "config/s3.yml", :path => "/:style/:id/:filename"
  	validates_attachment_content_type :avatar, :content_type => /\Aimage\/.*\Z/

	def type_is
		if genre_id
			type_of_writer = Genre.find_by id: genre_id
			type_of_writer.name
		end
	end

	def self.from_omniauth(auth)
	  where(provider: auth.provider, uid: auth.uid).first_or_create do |user|
	    user.email = auth.info.email
	    user.password = Devise.friendly_token[0,20]
	    user.name = auth.info.name   # assuming the user model has a name
	    # user.image = auth.info.avatar # assuming the user model has an image
	  end
	end

	# def self.new_with_session(params, session)
	#     super.tap do |user|
	#       if data = session["devise.twitter_data"] && session["devise.twitter_data"]["extra"]["raw_info"]
	#         user.email = data["email"] if user.email.blank?
	#       end
	#     end
 # 	end

	def am_writing?
		if !entries.empty?
			if !desired_interval.nil?
				if track_hours == true
						seconds_written = entries.where(created_at: (Time.now.end_of_day - desired_interval.day)..Time.now.end_of_day).sum("duration")
							if seconds_written < 3600 
								hours_written = 0
							else 
								hours_written = ChronicDuration.output(seconds_written, :limit_to_hours => true, :format => :short).to_i
							end

							if hours_written >= desired_amount
								writing = true
							else
								writing = false
							end
				else
					times_written = entries.where(created_at: (Time.now.midnight - desired_interval.day)..Time.now.midnight).length
					
					if times_written >= desired_amount
						writing = true
					else
						writing = false
					end
				end
			end
		else
			writing = true
		end
		writing
	end

	def desired_timeframe
		if desired_interval
			if desired_interval == 1
				return "day"
			elsif desired_interval == 7
				return "week"
			elsif desired_interval == 30
				return "month"
			end
		else
			return "undetermined"
		end		
	end

	def total_time_writing_this_week
		if !entries.empty?
			seconds_written = entries.where(created_at: (Time.now.end_of_day - 1.week)..Time.now.end_of_day).sum("duration")

			if seconds_written < 3600 
				hours_written = "less than 1 hour"
			else 
				amount = ChronicDuration.output(seconds_written, :limit_to_hours => true, :format => :short).to_i
				hours_written = "#{amount} hours"
			end
		end
		hours_written
	end

	def total_time_writing
		if entries
		 entries.sum("duration")
		end
	end

	def hours_or_times
		if track_hours == true
			metric = "hours"
		else
			metric = "times"
		end
	end

	def most_recent_goal
		if !projects.empty?
			if !entries.empty?
				most_recent_entry = entries.order('created_at').last
				most_recent_goal = goals.order('created_at').last

				if most_recent_entry.created_at > most_recent_goal.created_at
					latest_goal = most_recent_entry.goal
				else
					latest_goal = most_recent_goal
				end
			end
			# latest_goal = goals.order('created_at').last
		end
		latest_goal
	end

	def spark_line
		last_week = entries.order('created_at').last(7)
		array = []
		last_week.map do |entry|
			array << ChronicDuration.parse(entry.duration)
		end
		array.join(', ')
	end

	def deadlines
		if !projects.empty?
			upcoming = projects.where(deadline: Date.today..7.days.from_now)
			upcoming
		end
	end
end

app/controllers/users/omniauth_callbacks_controller.rb
class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  def twitter
    # You need to implement the method below in your model (e.g. app/models/user.rb)
    @user = User.from_omniauth(request.env["omniauth.auth"])

    if @user.persisted?
      sign_in_and_redirect @user #this will throw if @user is not activated
      set_flash_message(:notice, :success, :kind => "Twitter") if is_navigational_format?
    else
      session["devise.twitter_data"] = request.env["omniauth.auth"].uid
      redirect_to new_user_registration_url
    end
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy, :settings, :profile, :calendar]
  # before_filter :require_no_authentication, only: :create
  respond_to :html, :json
  # GET /users
  # GET /users.json
  # def index
  #   @users = User.all
  # end

  # GET /users/1
  # GET /users/1.json
  def show
    respond_to do |format|
      format.html
      format.js
    end
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
    respond_to do |format|
      format.html
      format.js
    end
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        format.html { redirect_to sign_in @user, :flash => { success: 'Your account has been successfully created. Please check your email to verify your account.'} }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  def calendar
    respond_to do |format|
      format.js
    end
  end

  def settings
    respond_to do |format|
      format.html
      format.js
    end
  end

  def profile
    respond_to do |format|
      format.html
      format.js
    end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, :flash => { success: 'User was successfully updated.'} }
        format.json { respond_with_bip(@user) }
        # format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit }
        format.json { respond_with_bip(@user) }
        # format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url, notice: 'User was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
      if @user.id != current_user.id 
        redirect_to home_index_path
      end
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      params.require(:user).permit(:name, :email, :location, :genre_id, :desired_amount, :desired_interval, :track_hours, :tag_list, :avatar)
    end
end

app/helpers/users_helper.rb
module UsersHelper
	def events_ajax_previous_link
	   ->(param, date_range) { link_to raw("&laquo;"), {param => date_range.first - 1.day}, remote: :true}
	end

	def events_ajax_next_link
    	->(param, date_range) { link_to raw("&raquo;"), {param => date_range.last + 1.day}, remote: :true}
	end
end

app/views/users/_calendar.html.erb
<%= month_calendar events: projects, previous_link: events_ajax_previous_link, next_link: events_ajax_next_link do |date, projects| %>


	<%= date.strftime("%e") %>
		<div class="calendar-entries tooltip">
		  	<% projects.each do |project| %>
			    <div class="calendar-entry">
			      <%= project.deadline %>
			    </div>
			<% end %>
		</div>
<% end %>

app/views/users/_form.html.erb
<%= form_for @user, :html => { :multipart => true } do |f| %>
  <% if @user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% @user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>


  <div id="target"><%= image_tag @user.avatar.url(:thumb) %>  </div>
  <%= f.file_field :avatar %>


  <div class="field">
    <%= f.label :name %>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :email %>
    <%= f.text_field :email %>
  </div>
  <div class="field">
    <%= f.label :location %>
    <%= f.text_field :location %>
  </div>
  <div class="field">
    <%= f.label :tag_list, "What kind of writer are you?" %>
    <%= f.text_field :tag_list %>
  </div>
  
  <div class="actions">
    <%= f.submit %>
  </div>
  <%= link_to 'Back', profile_user_path(@user), :remote => true %>
<% end %>

app/views/users/_profile.html.erb
<%= image_tag @user.avatar.url(:thumb) %>

<p><strong>Name:</strong>
              <%= @user.name %>
          </p>
          <p>
            <strong>Email:</strong>
            <%= @user.email %> <%# best_in_place @user, :email, :type => :input %>

          </p>
          <p>
            <strong>Location:</strong>
            <%= @user.location %>
          </p>
          <p>
            <strong>What kind of writer are you? </strong> 
            <%= @user.tag_list %>
          </p>
           <%= link_to 'Edit My Profile', edit_user_path(@user), :remote => true %> 

        

app/views/users/_settings.html.erb
<%= form_for(@user) do |f| %>
  <% if @user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% @user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

<div class="user-field-hide">
    <%= f.label :writing_goal %>
    <div class="user-writing-settings">
    I want to write <%= f.number_field :desired_amount %> <%= f.select :track_hours, options_for_select([['times', false], ['hours', true]], "#{@user.track_hours}") %> per <%= f.select :desired_interval, options_for_select([['day', 1], ['week', 7], ['month', 30]], "#{@user.desired_interval}")  %>
    </div>
  </div>

   <div class="actions">
    <%= f.submit "Update Settings"%>
  </div>

  <% end %>

app/views/users/calendar.js.erb
$('#deadline-view').html("<%= escape_javascript(render :partial => 'calendar', :projects => @user.projects) %>");

app/views/users/edit.html.erb
<h1>Editing user</h1>
<fieldset>
	<%= render 'form' %>
</fieldset>
<%= link_to 'Show', @user %> |
<%= link_to 'Back', user_path %>

app/views/users/edit.js.erb
$('#user-profile').html("<%= escape_javascript(render :partial => 'form', :user => @user) %>");
$('#user_tag_list').tagsInput();

$(function() {
  $('#user_avatar').on('change', function(event) {
         var files = event.target.files;
         var image = files[0]
         var reader = new FileReader();
         reader.onload = function(file) {
	         var img = new Image();
	         console.log(file);
	         img.src = file.target.result;
	         $('#target').html(img);
         	}
         reader.readAsDataURL(image);
         console.log(files);
     });
});

app/views/users/index.html.erb
<h1>Listing users</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Email</th>
      <th>Location</th>
      <th>Genre</th>
      <th>Desired amount</th>
      <th>Desired interval</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= user.name %></td>
        <td><%= user.email %></td>
        <td><%= user.location %></td>
        <td><%= user.genre_id %></td>
        <td><%= user.desired_amount %></td>
        <td><%= user.desired_interval %></td>
        <td><%= link_to 'Show', user %></td>
        <td><%= link_to 'Edit', edit_user_path(user) %></td>
        <td><%= link_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New User', new_user_path %>

app/views/users/new.html.erb
<h1>New user</h1>

<%= render 'form' %>

<%= link_to 'Back', users_path %>

app/views/users/profile.js.erb
$('#user-profile').html("<%= escape_javascript(render :partial => 'profile', :user => @user) %>");

app/views/users/settings.html.erb
<h1>Editing Settings</h1>
<fieldset>
	<%= render 'settings' %>
</fieldset>
<%= link_to 'Show', @user %> |
<%= link_to 'Back', user_path %>

app/views/users/settings.js.erb
$('#settings-test').html("<%= escape_javascript(render :partial => 'settings', :user => @user) %>");

app/views/users/show.html.erb
<article class="article">

  <p>&nbsp;</p>

  <ul class="accordion-tabs">
    <li class="tab-header-and-content">
      <a href="#" class="is-active tab-link">Settings</a>
      <div class="tab-content">
        <span class="invisible">Ut laoreet augue et neque pretium non sagittis nibh pulvinar. Etiam ornare tincidunt orci quis ultrices. </span>
        <fieldset class="user-tabs">
        <h3><% if @user.am_writing? == true %>
              You are writing!
            <% else %>
              You need to write more.
            <% end%></h3>  <p>This is the heart of the writetrack system. You tell us how much you want to write, per day, per week, per month and whether or you want to track the hours you spend or the times you write, and we will help you meet your goal.</p> <p><% if @user.am_writing? == true %>
              Currently, you are reaching your goal.
            <% else %>
              Currently, you are not meeting your stated goal.
            <% end%></p>
            <fieldset>
            <div id="settings-test">
           
            I want to write<strong> <%= @user.desired_amount %> </strong>
            <%= @user.hours_or_times %> per <strong> <%= @user.desired_timeframe %></strong>.
            
          </p> 
          <%= link_to 'Edit My Settings', settings_user_path(@user), :remote => true %> 
          </div>
          </fieldset>
         
         </fieldset>
      </div>
    </li>
    <li class="tab-header-and-content">
      <a href="#" class="tab-link">Profile</a>
      <div class="tab-content">
       <span class="invisible">Ut laoreet augue et neque pretium non sagittis nibh pulvinar. Etiam ornare tincidunt orci quis ultrices. </span>
        <fieldset class="user-tabs">

           <div id="user-profile">
          <%= render 'profile' %>
           </div>
        </fieldset>
      </div>
    </li>
    <li class="tab-header-and-content">
      <a href="#" class="tab-link">Deadlines</a>
        <div class="tab-content">
        <span class="invisible">Ut laoreet augue et neque pretium non sagittis nibh pulvinar. Etiam ornare tincidunt orci quis ultrices.</span>
         
        <fieldset class="user-tabs">
          <h4>Upcoming Project Deadlines</h4>
          
          <div id="deadline-view">
            <%# render partial: 'calendar', locals: { projects: @user.projects }%>
          </div>
                
                
        </fieldset>    
      </div>
    </li>
    <li class="tab-header-and-content">
      <a href="#" class="tab-link">Stats</a>
      <div class="tab-content">
        <span class="invisible">Ut laoreet augue et neque pretium non sagittis nibh pulvinar. Etiam ornare tincidunt orci quis ultrices.</span>
        <fieldset class="user-tabs">
          <div class="charter">
           <canvas id="myChart" width="150" height="150"></canvas>
          </div>
            <p>You spent <%= @user.total_time_writing_this_week %> writing this week. </p>
        </fieldset>
      </div>
    </li>
  </ul>

<script>
   var data = {
    labels: ["Friday", "Saturday", "Sunday", "Monday", "Tuesday", "Wednesday", "Thursday"],
    datasets: [
        {
            label: "My Second dataset",
            fillColor: "rgba(242,0,0,0.8)",
            strokeColor: "rgba(155,0,0,0.8)",
            highlightFill: "rgba(151,187,205,0.75)",
            highlightStroke: "rgba(151,187,205,1)",
            data: [<%= @user.spark_line %>]
        }
    ]
};
var ctx = $("#myChart").get(0).getContext("2d");
var myNewChart = new Chart(ctx);
var myBarChart = new Chart(ctx).Bar(data);
</script>

</article>

<section class="stats">
      <div class="quotes">
        <h3>“You can't wait for inspiration. You have to go after it with a club.”  </h3>
        <p>&ndash; Jack London</p>
      </div>
  </section>