config/routes.rb
Rails.application.routes.draw do
  get 'home/index'
  get 'home/about'
  get 'projects/archive'
  devise_for :users, :controllers => { :registrations => "registrations", :omniauth_callbacks => "users/omniauth_callbacks" }
  resources :projects, shallow: true do
    member do
        get :calendar
      end
    resources :goals do
      member do
        get :calendar
        get :list
      end
    end
    resources :entries
  end

  resources :users, only: [:show, :edit, :update] do 
    member do
      get :settings
      get :profile
    end
    devise_scope :user do
      get 'sign_out', :to => 'devise/sessions#destroy', :as => :destroy_user_session
    end
  end
  
 
  

  root 'home#index'

end

app/models/project.rb
class Project < ActiveRecord::Base
	has_many :goals, :dependent => :destroy
	has_many :entries, through: :goals, :dependent => :destroy
	belongs_to :user
	belongs_to :project_type
	accepts_nested_attributes_for :goals
	accepts_nested_attributes_for :entries
	include AASM
	extend SimpleCalendar
  	has_calendar :attribute => :deadline


	def type_is
			project_type = ProjectType.find_by id: project_type_id
			project_type.name
	end

	def most_recent_entry
		if !entries.empty?
			entries.order('created_at').last
		end
	end

	def most_recent_goal
		most_recently_created_goal = goals.order('created_at').last
		if !entries.empty?
			most_recent_entry = entries.order('created_at').last

			if most_recent_entry.created_at > most_recently_created_goal.created_at
				latest_goal = most_recent_entry.goal
			else
				latest_goal = most_recently_created_goal
			end
		end
		latest_goal
	end

	def total_time_spent
		if entries
		 entries.sum("duration")
		end
	end

	def spark_line
		last_week = entries.order('created_at').last(7)
		array = []
		last_week.map do |entry|
			array << ChronicDuration.parse(entry.duration)
		end
		array.join(', ')
	end

	aasm do
		state :active, :initial => true
		state :paused
		state :completed
		state :archived

		# event :deadline_passed do
		# 	transitions :from => [:overdue, :active], :to => :overdue
		# end

		# event :deadline_future do
		# 	transitions :from => [:overdue, :archive, :active], :to => :active
		# end

	end

	# def deadline_check
	# 	if deadline
	# 		if deadline > Date.today
	# 			deadline_passed
	# 		elsif deadline < Date.today
	# 			deadline_future
	# 		end
	# 	end
	# end
end

app/models/project_type.rb
class ProjectType < ActiveRecord::Base
	has_many :projects
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  before_action :set_project, only: [:show, :edit, :update, :destroy, :calendar]
  layout "projects_edit", only: [:edit]
  

  # GET /projects
  # GET /projects.json
  def index
    @projects = if current_user
        current_user.projects.all
      else
        redirect_to home_index_path
      end
  end

  # GET /projects/1
  # GET /projects/1.json
  def show
    # @goal = Goal.new
  end

  # GET /projects/new
  def new
    @project = Project.new
  end

  # GET /projects/1/edit
  def edit
  end

  # POST /projects
  # POST /projects.json
  def create
    @project = Project.new(project_params)
    @project.user_id = current_user.id
    respond_to do |format|
      if @project.save
        format.html { redirect_to project_goals_path(@project), :flash => { success: 'Project was successfully created.'} }
        format.json { render :show, status: :created, location: @project }
      else
        format.html { render :new }
        format.json { render json: @project.errors, status: :unprocessable_entity }
      end
    end
  end

  def calendar
    respond_to do |format|
      format.js
    end
  end

  # PATCH/PUT /projects/1
  # PATCH/PUT /projects/1.json
  def update
     # @project.deadline_check
    respond_to do |format|
      if @project.update(project_params)
        format.html { redirect_to projects_path, :flash => { success: 'Project was successfully updated.'} }
        format.json { render :show, status: :ok, location: @project }
      else
        format.html { render :edit, :flash => { error: 'The project was not able to be saved.'} }
        format.json { render json: @project.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /projects/1
  # DELETE /projects/1.json
  def destroy
    @project.destroy
    respond_to do |format|
      format.html { redirect_to projects_url, notice: 'Project was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def archive
     @projects = if current_user
        current_user.projects.archived.all
      else
        redirect_to home_index_path
      end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_project
      @project = Project.find(params[:id])
      if @project.user_id != current_user.id 
        redirect_to home_index_path
      end
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def project_params
      params.require(:project).permit(:name, :project_type_id, :description, :deadline, :aasm_state)
    end
end

app/helpers/projects_helper.rb
module ProjectsHelper
	def events_ajax_previous_link
 		->(param, date_range) { link_to raw("&laquo;"), {param => date_range.first - 1.day}, remote: :true}
	end

	def events_ajax_next_link
		->(param, date_range) { link_to raw("&raquo;"), {param => date_range.last + 1.day}, remote: :true}
	end
end

app/views/projects/_calendar.html.erb
  <%= month_calendar events: projects, previous_link: events_ajax_previous_link, next_link: events_ajax_next_link do |date, projects| %>

    <%= date.strftime("%e") %>
     <div class="calendar-entries tooltip">
        <% projects.each do |project| %>
          <div class="calendar-entry">
            <%= link_to "", project_path(project) %>
          </div>
        <% end %>
      </div>
  <% end %>

app/views/projects/_form.html.erb
<%= form_for(@project) do |f| %>
  <% if @project.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@project.errors.count, "error") %> prohibited this project from being saved:</h2>

      <ul>
      <% @project.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :project_type %>
    <%= f.select :project_type_id, options_from_collection_for_select(ProjectType.all, :id, :name, "#{@project.project_type_id}") %>
  </div>


  <div class="field">
   <%# aasm_states_array = [['Active', 'active' ], ['Archived', 'archived']] %>
   <%# f.label :status %>
   <%# f.select :aasm_state,  options_for_select(aasm_states_array) %>
  </div>

  <div class="field">
      <%= f.label :description %>
      <%= f.text_field :description %>
  </div>
  <div class="field">
      <%= f.label :deadline %>
      <%= f.date_field :deadline %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/projects/_project.html.erb
<div class="card project">
  <div class="card-image">
      <h3 class="card-image title"><%= link_to project.name, project_goals_path(project) %></h3> 
  </div>

  <div class="card-header">
    <%= project.type_is.capitalize %>
  </div>

  <div class="card-copy">
    <% if project.deadline %>
      <p>Deadline: <%= project.deadline.strftime("%A, %b %d") %> </p>
    <% end %>
  </div>

  <div class="card-stats">
   
   <%= render :partial => "project_stats", :locals => { :project => project } %>

    <ul class="edit-button">
      <li ><span class="edit"><%= link_to 'View', project_goals_path(project) %></span></li>
    </ul>
  </div>
</div> 

app/views/projects/_project_stats.html.erb
<ul>
  <% if project.total_time_spent == 0 %>
  	<li>0<span>Time Spent</span></li>
  <% else %>
  	<li>
  		<%= ChronicDuration.output(project.total_time_spent, :format => :short, :units => 2) %><span>Time Spent</span>
  	</li>
  <% end %>

  <% if project.entries %>
    <li>
    	<%= project.goals.length %><span>Goals</span>
    </li>
  <% end %>

  <% if project.entries %>
       <li><%= project.entries.length %><span>Entries</span></li>
  <% end %>

  <% if project.deadline %>
    <% if time_left(project.deadline) > 0 %>
      <li><%= time_left(project.deadline) %><span>Days Left</span></li>
    <% elsif time_left(project.deadline) == 0 %>
      <li>Project<span>Due Today!</span></li>
    <% elsif time_left(project.deadline) < 0 %>
      <li class="overdue"><%= time_left(project.deadline) * -1 %>d<span>Overdue!</span></li>
    <% end %>
  <% end %>
</ul>

app/views/projects/archive.html.erb
<article class="article">
  <div class="breadcrumb">
    <%= link_to 'Dashboard', home_index_path %>
    <%= link_to 'My Projects', projects_path, class: "current-selection" %>
  </div>

  <h1 class="main-title">Archived Projects</h1>

  <div class="project-button"><%= link_to 'New Project', new_project_path %></div>

      <% @projects.each do |project| %>
		<% if project.active? %>
		<% else %>
	        <div class="card project">
	          <div class="card-image">
	              <h3 class="card-image title"><%= link_to project.name, project_goals_path(project) %></h3> 
	          </div>

	          <div class="card-header">
	            <%= project.type_is.capitalize %>
	          </div>

	          <div class="card-copy">
	            <% if project.deadline %>
	              <p>Deadline: <%= project.deadline.strftime("%A, %b %d") %> </p>
	            <% end %>
	            <% if project.aasm_state %>
	              <p>Status: <%= project.aasm_state %> </p>
	            <% end %>
	          </div>

	          <div class="card-stats">
	            <ul>
	              <li><%= ChronicDuration.output(project.total_time_spent, :format => :short, :units => 2) %><span>Time Spent</span></li>
	              <% if project.entries %>
	                <li><%= project.goals.length %><span>Goals</span></li>
	              <% end %>
	              <% if project.deadline %>
	                <li><%= time_left(project.deadline) %><span>Days Left</span></li>
	              <% end %>
	            </ul>

	            <ul class="edit-button">
	              <li ><span class="edit"><%= link_to 'View', project_goals_path(project) %></span></li>
	            </ul>
	          </div>
	        </div>
        <% end %>
      <% end %>

app/views/projects/calendar.js.erb
$('#deadline-view').html("<%= escape_javascript(render :partial => 'projects/calendar', :projects => @projects) %>");
 $('.calendar-entry').parent().parent().addClass('entry-date tooltip-item');
 $('.calendar-entry').on('click', function() {
 	var self = $(this);
 	self.children()[0].click();
 });
 $('.prev-month, .next-month').addClass('old-month');

app/views/projects/edit.html.erb
<fieldset>
	<%= render 'form' %>
</fieldset>
 <%= link_to 'Delete this Project', @project, method: :delete, data: { confirm: 'Are you sure?' } %>

app/views/projects/index.html.erb
<article class="article">
  <div class="breadcrumb">
    <%= link_to 'Dashboard', home_index_path %>
    <%= link_to 'My Projects', projects_path, class: "current-selection" %>
  </div>

  <h1 class="main-title">My Projects</h1>

  <div class="project-button"><%= link_to 'New Project', new_project_path %></div>

    <%= render @projects %>
    
  <% if !@projects.archived.empty? %>
    <%= link_to 'Archived Projects', projects_archive_path %>
  <% end %>
  

</article>


<section class="stats">
  <div class="quotes">
      <h3>“If there's a book that you want to read, but it hasn't been written yet, then you must write it.”</h3>
      <p>&ndash; Toni Morrison</p>
  </div>
</section>

app/views/projects/new.html.erb
<article class="article">
	<div class="breadcrumb">
	  <%= link_to 'Dashboard', home_index_path %>
	  <%= link_to 'My Projects', projects_path %>
	  <a href="#" class="current-selection">Project</a>
  	</div>


	<h1 class="main-title">New project</h1>
	<div class="card project">
  		<div class="card-image">
      	</div>

		<div class="card-copy">
			<fieldset>
				<%= render 'form' %>
			</fieldset>
		</div>
</article>

app/views/projects/show.html.erb
<article class="article">
	<div class="breadcrumb">
	  <%= link_to 'Dashboard', home_index_path %>
	  <%= link_to 'All Projects', projects_path %>
	</div>

<h1>"<em><%= @project.name %></em>"</h1>
<h3>Project Dashboard</h3>
  <strong>Type:</strong> <%= @project.type_is %> <br>
  <% if @project.deadline %>
 	 <strong>Deadline:</strong> <%= @project.deadline.strftime("%A, %b %d")%> <br>
 	 <% if time_left(@project.deadline) >= 0 %>
		You have <%= time_left(@project.deadline) %> days left to finish this project. <br>
	<% else %>
		<strong>Your deadline is past due!</strong> <br>
	<% end %>
<% end %>
<h4><%= link_to "Project History", project_goals_path(@project) %></h4>


<p>&nbsp;</p>

<% if @project.most_recent_entry == nil %>
	<p>How far along are you in your writing? <br> This app uses goals to track your writing progress. </p>
	<%= link_to "Let's make some goals", new_project_goal_path(@project) %>
<% else %>
	<strong>Most Recent Goal:</strong> <%= @project.most_recent_goal.type_is %> >>> <div class="write-button"><%= link_to "Write Now!", new_project_entry_path(@project.id, :goal_id => @project.most_recent_goal.id) %> </div> <br>
<% end %>
</article>
<section class="stats">
	<% if @project.entries.empty? %>
	<% else %>
		<div>
			<h3>Stats</h3>
				<p>You've spent <%= distance_of_time_in_words(@project.total_time_spent) %> on "<em><%= @project.name %></em>"</p>
				<p>Your time over the last 7 days: <span class="inlinesparkline"><%= @project.spark_line %></span>
				</p>
		</div>
		
	<% end %>



 | <%= link_to 'Edit This Project', edit_project_path(@project) %> |
<%= link_to 'My Projects', projects_path %>

</section>