config/routes.rb
Rails.application.routes.draw do
  get 'home/index'
  get 'home/about'
  get 'projects/archive'
  devise_for :users, :controllers => { :registrations => "registrations", :omniauth_callbacks => "users/omniauth_callbacks" }
  resources :projects, shallow: true do
    member do
        get :calendar
      end
    resources :goals do
      member do
        get :calendar
        get :list
      end
    end
    resources :entries
  end

  resources :users, only: [:show, :edit, :update] do 
    member do
      get :settings
      get :profile
    end
    devise_scope :user do
      get 'sign_out', :to => 'devise/sessions#destroy', :as => :destroy_user_session
    end
  end
  
 
  

  root 'home#index'

end

app/models/goal.rb
class Goal < ActiveRecord::Base
	has_many :entries, :dependent => :destroy
	belongs_to :projects
	belongs_to :goal_type
	# include AASM
	extend SimpleCalendar
  	has_calendar :attribute => :deadline

	def type_is
		if goal_type
			if goal_type_id == 4 
				type_is = "writing #{draft_number.ordinalize} draft"
			else
				goal_type = GoalType.find_by id: goal_type_id
				type_is = goal_type.name
			end
			type_is
		end
	end

	def type_is_dashboard
		if goal_type
			if goal_type_id == 4 
				type_is = "writing the #{draft_number.ordinalize} draft of"
			else
				goal_type = GoalType.find_by id: goal_type_id
				type_is = goal_type.name
			end
			type_is
		end
	end

	def project_name
		project = Project.find_by id: project_id
		project.name
	end

	def project
		project = Project.find_by id: project_id
		project
	end

	def user_id
		project = Project.find_by id: project_id
		user_id = project.user_id
		user_id
	end

	def total_time_spent
		if entries
		 entries.sum("duration")
		end
	end

	def progress
		if entries
			done_so_far = entries.sum("amount_done")
			unless done_so_far == 0
				progress = ((done_so_far.to_f / metric_target.to_f) * 100).floor
			end
		else
			progress = 1
		end
		if progress == nil
			progress = 0
		elsif progress >= 101
			progress = 101
		end
		progress
	end

	def metrics_progress
		if entries
			done_so_far = entries.sum("amount_done")
		else
			done_so_far = 1
		end
		done_so_far
	end

	def made_on
		created_at.localtime.strftime("%b %e, %l:%M %p")
	end

	def metric_type_is
		if metric_id
			if metric_id == 5
				metric_type = metric_name
			else
				metric_type = Metric.find_by id: metric_id
				metric_type.name
			end
		end
	end

	def spark_line
		last_week = entries.order('created_at').last(7)
		array = []
		last_week.map do |entry|
			array << ChronicDuration.parse(entry.duration)
		end
		array.join(', ')
	end
	
	# aasm do
	# 	state :active, :initial => true
	# 	state :paused
	# 	state :completed
	# 	state :archived

	# 	# event :deadline_passed do
	# 	# 	transitions :from => [:overdue, :active], :to => :overdue
	# 	# end

	# 	# event :deadline_future do
	# 	# 	transitions :from => [:overdue, :archive, :active], :to => :active
	# 	# end
	# end

	# def deadline_check
	# 	if deadline
	# 		if deadline > Date.today
	# 			deadline_passed
	# 		elsif deadline < Date.today
	# 			deadline_future
	# 		end
	# 	end
	# end

end

app/models/goal_type.rb
class GoalType < ActiveRecord::Base
	has_many :goals
end

app/controllers/goals_controller.rb
class GoalsController < ApplicationController
	before_action :set_goal, only: [:show, :edit, :update, :destroy, :calendar, :list]
	

	def index
		@goals = Project.find(params[:project_id]).goals
		@project = Project.find(params[:project_id])
		render layout: "goals_index"
			if @project.user_id != current_user.id 
	        	redirect_to home_index_path
	      	end
	end
	def show
		# respond_to do |format|
		# 	format.html
		# 	format.js 
		# end
	end
	def calendar
		respond_to do |format|
			format.js
		end
	end
	def list
		respond_to do |format|
			format.js
		end
	end
	def new
		@project = Project.find(params[:project_id])
		@goal = Goal.new
		render layout: "goals_new"
	end

	def create
		@goal = Goal.new(goal_params)
		@project = @goal.project_id
		if @goal.save
			redirect_to goal_path(@goal)
		else
			render "/projects/show"
		end
	end

	def edit	
	end

	def update
		# @goal.deadline_check
		 if @goal.update(goal_params)
		 	flash[:success] = "Goal was successfully updated!"
		 	redirect_to goal_path
		 else
		 	render :edit
		 end
	end


	def destroy
		@goal.destroy 
		redirect_to project_goals_path(@goal.project), :flash => { :notice => "Goal successfully deleted." }
	end

	private
	def goal_params
		params.require(:goal).permit(:name, :goal_type_id, :amount_done, :deadline, :metric_id, :metric_target, :metric_name, :project_id, :draft_number)
	end

	def set_goal
      @goal = Goal.find(params[:id])
       if @goal.user_id != current_user.id 
        redirect_to home_index_path
      end
    end
end

app/helpers/goals_helper.rb
module GoalsHelper
	def events_ajax_previous_link
	   ->(param, date_range) { link_to raw("&laquo;"), {param => date_range.first - 1.day}, remote: :true}
	end

	def events_ajax_next_link
    	->(param, date_range) { link_to raw("&raquo;"), {param => date_range.last + 1.day}, remote: :true}
	end

end

app/views/goals/_calendar.html.erb
<%= month_calendar events: @goal.entries, previous_link: events_ajax_previous_link, next_link: events_ajax_next_link do |date, entries| %>


	<%= date.strftime("%e") %>
		<div class="calendar-entries tooltip">
		  	<% entries.each do |entry| %>
			    <div class="calendar-entry">
			      <%= link_to "", entry_path(entry) %>
			    </div>
			<% end %>
		</div>
<% end %>

app/views/goals/_entries_list.html.erb
<table>
	<tr class="entry-list-header" >
		<th>Date</th>
		<th>Duration</th>
		<% if @goal.metric_id != 5 %>
			<th><%= @goal.metric_type_is.capitalize %> </th>
		<% end %>
		<th>Journal</th>
	</tr>
		<% @goal.entries.order("created_at desc").each do |entry| %>
		<tr>
			<td>
				<span class="edit-entry"><%= link_to entry.created_at.strftime("%b %e"), entry_path(entry) %> </span> 
			</td>
			<td>
				<p><%= entry.duration %></p> 
			</td>
			<% if @goal.metric_id != 5 %>
				<td>
					<p><%= entry.amount_done %></p>
				</td>
			<% end %>

			<td>
				<% if entry.journal %>
					<p><em><%= entry.journal.truncate(35) %></em></p>
				<% end %>
			</td>
			<!-- <td>
				<%# link_to 'View', entry_path(entry) %>
			</td> -->
		</tr>
	<% end %>
</table>

app/views/goals/_form.html.erb
<%= form_for [@project, @goal] do |f| %>
	<% if @goal.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@goal.errors.count, "error") %> prohibited this product from being saved:</h2>

      <ul>
      <% @goal.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  
  
    <div class="field">
        <%= f.label :goal_type %> 

        <div class="draft-number">
            <%= f.select :goal_type_id, options_from_collection_for_select(GoalType.all, :id, :name, "#{@goal.goal_type_id}") %>
            <span id="conditional-draft-number">
                draft number <%= f.number_field :draft_number %>
            </span>
        </div>
  </div>
  <div class="field">
    <%= f.label :description %> 
    <%= f.text_field :name %> 
  </div>
  <div class="field">
    <%= f.label :deadline %> 
    <%= f.date_field :deadline%> 
  </div>
<%# aasm_states_array = @goal.aasm.states.map(&:name) %>
  <div class="field">
   <%# f.label :status %>
   <%# f.select :aasm_state,  options_for_select(aasm_states_array) %>
  </div>

      <%= label_tag(:metric_check, "Track metrics") %> 
      <label class="metric-check">
      <%= check_box_tag(:metric_check) %> <div class="checkbox"></div>
      </label>
      
      <div class="goal-field-hide">
        <fieldset> 
            <div class="goal-settings">
                To achieve this goal, <br> I will write
                <%= f.number_field :metric_target %>
                <%= f.select :metric_id, options_from_collection_for_select(Metric.all, :id, :name, "#{@goal.metric_id}") %> <%= f.text_field :metric_name  %> 
            </div>
          </fieldset>
      </div>
      
  
  <% if @project == nil %>
      <%= f.hidden_field(:project_id, :value => @goal.project.id) %>
    <% else %>
      <%= f.hidden_field(:project_id, :value => @project.id) %>
  <% end %>
 <br>
  <%= f.submit %>

<% end %>

app/views/goals/_goal.html.erb
<div class="card">
  <div class="card-image goal">
      <h6 class="goal">Goal: <%= link_to goal.type_is.capitalize, goal_path(goal) %></h6> 
  </div>

  <div class="card-header">
    
  </div>

    <div class="card-copy">
      <% if goal.deadline %>
      <p>Deadline: <%= goal.deadline.strftime("%A, %b %d") %> </p>
    <% end %>
  </div>

  <div class="card-stats">
    <ul>
      <%= render :partial => "goal_stats", locals: {goal: goal} %>
    </ul>
    <ul class="edit-button">
      <li><span class="edit"><%= link_to 'View', goal_path(goal) %></span></li>
      <li ><span class="write-now"><%= link_to "Write Now!", new_project_entry_path(:project_id => goal.project_id, :goal_id => goal) %></span></li>
    </ul>
  </div>
</div>

app/views/goals/_goal_stats.html.erb
<li>
	<%= ChronicDuration.output(goal.total_time_spent, :format => :short, :units => 2) %><span>Time Spent</span>
</li>
<% if goal.entries %>
	<li><%= goal.entries.length %><span>Entries</span></li>
<% end %>

<%#  Deadline logic %>
<% if goal.deadline %>
	<% if time_left(goal.deadline) > 0 %>
		<li><%= time_left(goal.deadline) %><span>Days Left</span></li>
	<% elsif time_left(goal.deadline) == 0 %>
		<li>Goal<span>Due Today!</span></li>
	<% elsif time_left(goal.deadline) < 0 %>
		<li class="overdue"><%= time_left(goal.deadline) * -1 %>d<span>Overdue!</span></li>
	<% end %>
<% end %>

app/views/goals/calendar.js.erb
$('#entries-view').html("<%= escape_javascript(render :partial => 'calendar', :goal => @goal) %>");
 $('.calendar-entry').parent().parent().addClass('entry-date tooltip-item');
 $('.calendar-entry').on('click', function() {
 	var self = $(this);
 	self.children()[0].click();
 });
 $('.prev-month, .next-month').addClass('old-month');

app/views/goals/edit.html.erb
<fieldset>
	<%= render 'form' %>

	<%= link_to 'Back', goal_path(@goal), class: "edit" %> | <%= link_to 'Delete this goal', @goal, method: :delete, data: { confirm: 'Are you sure?' } %>
</fieldset>

app/views/goals/index.html.erb
        <div class="card-copy">
            <% if @project.deadline %>
              <p>Deadline: <%= @project.deadline.strftime("%A, %b %d") %> </p>
            <% end %>
		</div>

		<div class="card-stats">
	        <%= render :partial => "projects/project_stats", locals: {project: @project} %>
    	</div>
    	<div class="card-stats">
	        <ul class="edit-button">
	        	
	          	<li ><span class="edit"><%= link_to 'Edit', edit_project_path(@project) %></span></li>

	          	<li><span class="edit"><%= link_to "New Goal", new_project_goal_path(@project) %></span></li>
	        </ul>
	    </div>
	  
		<div class="inner-project">
			<%= render @goals %>
		</div>
	


	

app/views/goals/list.js.erb
$('#entries-view').html("<%= escape_javascript(render :partial => 'entries_list', :goal => @goal) %>");

app/views/goals/new.html.erb
<fieldset>
	<%= render 'form' %>

</fieldset>
	

app/views/goals/show.html.erb
	<div class="card-header">

		<% if @goal.deadline %>
			<p>Deadline: <%= @goal.deadline.strftime("%A, %b %d") %> </p>
		<% end %>
		
	</div>

	<div class="card-copy">
	Started: <%= @goal.created_at.strftime("%A, %b %d") %> <br>
	<% if !@goal.name.empty? %>
		Description: <%= @goal.name %> <br>
	<% end %>
	Your last 7 days: <span class="inlinesparkline"><%= @goal.spark_line %></span>
	</div>

	<div class="card-stats">
		<div class="left-side">
			<ul>
				<%= render :partial => "goal_stats", locals: {goal: @goal} %>
			</ul>
		</div>
		<div class="goal-stat-section">
				<% if @goal.metric_id == nil || @goal.metric_id == 5 %>
				<% else %>
				<div class="progress-bar-indication">
						<span class="meter" style="width: <%= @goal.progress %>%">
						<p><%= @goal.progress %>%</p>
						</span>
				</div>
				<span class="legend">
						<% if @goal.progress >= 100 %>
							Goal Target of <%= number_with_delimiter(@goal.metric_target) %> <%= @goal.metric_type_is %> met!
						<% else %>
							<%= number_with_delimiter(@goal.metrics_progress) %> of <%= number_with_delimiter(@goal.metric_target) %> <%= @goal.metric_type_is %> written...
					<% end %>
					</span>
			<% end %>
		</div>
	</div>

	<div class="entries">
		<div class="small-write">
			<span class="write-now"><%= link_to "Write Now!", new_project_entry_path(:project_id => @goal.project_id, :goal_id => @goal) %></span>
			<div class="goal-edit"><span class="edit"><%= link_to 'Edit', edit_goal_path(@goal) %></span></div>
		</div>
			<h5>Writing Entries </h5>


			<div class="button-group">
			  <label>
			    <input type="radio" name="button-group" value="list" checked>
			    <span class="button-group-item"><%= link_to "List", list_goal_path, :remote => true %></span>
			  </label>
			  <label>
			    <input type="radio" name="button-group" value="other-item">
			    <span class="button-group-item"><%= link_to "Calendar", calendar_goal_path, :remote => true %></span>
			  </label>
			</div>
			
			<div id="entries-view">
				<%= render 'entries_list' %>
			</div>
	