config/routes.rb
Rails.application.routes.draw do
  get 'home/index'
  get 'home/about'
  get 'projects/archive'
  devise_for :users, :controllers => { :registrations => "registrations", :omniauth_callbacks => "users/omniauth_callbacks" }
  resources :projects, shallow: true do
    member do
        get :calendar
      end
    resources :goals do
      member do
        get :calendar
        get :list
      end
    end
    resources :entries
  end

  resources :users, only: [:show, :edit, :update] do 
    member do
      get :settings
      get :profile
    end
    devise_scope :user do
      get 'sign_out', :to => 'devise/sessions#destroy', :as => :destroy_user_session
    end
  end
  
 
  

  root 'home#index'

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Write Track.co</title>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>
    <meta name="viewport" content="initial-scale=1, maximum-scale=1">
    <%= favicon_link_tag 'apple-touch-icon-iphone.png', rel: 'apple-touch-icon', type: 'image/png' %>
    <%= favicon_link_tag 'apple-touch-icon-ipad.png', rel: 'apple-touch-icon', type: 'image/png', sizes: '76x76' %>
    <%= favicon_link_tag 'touch-icon-iphone-retina.png', rel: 'apple-touch-icon', type: 'image/png', sizes: '120x120' %>
    <%= favicon_link_tag 'touch-icon-ipad-retina.png', rel: 'apple-touch-icon', type: 'image/png', sizes: '152x152' %>
  </head>

  <body>
    <div class="wrapper-for-content-outside-of-footer texture">
      <header class="navigation">
        <div class="navigation-wrapper">
          
             <%= link_to image_tag("writetrackmark.png", alt: "writetrack"), home_index_path, class: "logo" %><%= image_tag("writetracktext.png", alt: "get on the write track.", class: "secret")  %>
          
            <% if current_user %>
              <a href="" class="navigation-menu-button" id="js-mobile-menu">
              MENU</a>
              <%= link_to "Log Out", destroy_user_session_path(@user), :method => :delete, class: "sign-up secret" %>
            <% else %>
              <%= link_to "Log in", new_user_session_path, class: "log-in" %> or <%= link_to "Sign up", new_user_registration_path, class: "sign-up" %>
            <% end %>
          <div class="nav">
            <ul id="navigation-menu">
              <% if current_user %>
                <li class="nav-link"><%= link_to 'Projects', projects_path %></li>
                <li class="nav-link"><%= link_to 'Settings', user_path(current_user) %></a></li>
                <li class="nav-link"><a href="javascript:void(0)"> <%= link_to 'About', home_about_path %></a></li>
                <li class="nav-link"> <%= link_to "Log Out", destroy_user_session_path(@user), :method => :delete, class: "inverted-secret" %></li>
                <% end %>
            </ul>
          </div>
        </div>
      </header>
    

    
    <% flash.each do |key, value| %>
      <%= content_tag :div, value, class: "flash #{key}" %>
    <% end %>

      <div id="content">
        <%= content_for?(:content) ? yield(:content) : yield %>
      </div>  


      <div class="push"></div>
    </div>

    <footer class="footer-2">
      <div class="footer-logo">
        <%= image_tag("writetrackmarkfooter.png", alt: "writetrack") %>
      </div>
        <ul>
          <!-- <li><a href="javascript:void(0)">About</a></li> -->
          <li><a href="mailto:ward@minnis.net">Contact</a></li>
          <!-- <li><a href="javascript:void(0)">Products</a></li> -->
        </ul>

        <div class="footer-secondary-links">
          <ul>
            <li><a href="javascript:void(0)">Terms and Conditions</a></li>
            <li><a href="javascript:void(0)">Privacy Policy</a></li>
          </ul>

          <ul class="footer-social">
            <li><a href="https://twitter.com/writetrackco">
              <img src="https://raw.githubusercontent.com/thoughtbot/refills/master/source/images/twitter-logo-circle.png" alt="Twitter">
            </a></li>
          </ul>
        </div>

    </footer>
  </body>
</html>

app/views/layouts/entries.html.erb
<% content_for :content do %>
	<article class="article">
		<% if @goal == nil %>
			<% @goal = @entry.goal %>
		<% end %>

		<%= render "breadcrumb" %>
		

		<h1 class="main-title">Journal Entry</h1>
		
		<div class="card project">
	    	<div class="card-image">
	        	<h3 class="card-image title"><%= @goal.project.name %></h3> 
	        </div>
	        <div class="inner-project">
				<div class="card">
					<div class="card-image goal">
							<h6 class="goal"><%= @goal.type_is.capitalize %></h6> 

					</div>

					<div class="card-header">

					<%= content_for?(:entries_content) ? yield(:entries_content) : yield %>

					</div>
				</div>
			</div>
		</div>
	</article>
<% end %>

<%= render template: "layouts/application" %>

app/views/layouts/goals.html.erb
<% content_for :content do %>
	<article class="article">
		<div class="breadcrumb">
		  <%= link_to 'Dashboard', home_index_path %>
		  <%= link_to 'My Projects', projects_path %>
		  <%= link_to 'Project', project_goals_path(@goal.project) %>
		  <%= link_to 'Goal', goal_path(@goal), class: "current-selection" %>
		</div>

		<h1 class="main-title">Goal Details</h1>

		<div class="card project">
	    	<div class="card-image">
	        	<h3 class="card-image title"><%= @goal.project.name %></h3> 
	        </div>
	        <div class="inner-project">
				<div class="card">
					<div class="card-image goal">
						<h6 class="goal"><%= @goal.type_is.capitalize %></h6> 
					</div>
					
					<%= content_for?(:goals_content) ? yield(:goals_content) : yield %>

				</div>
			</div>
		</div>
	</article>

	<section class="stats">
			<div class="quotes">
				<h3>“There is nothing to writing. All you do is sit down at a typewriter and bleed.” </h3>
				<p>&ndash; Ernest Hemingway</p>
			</div>
	</section>
<% end %>
<%= render template: "layouts/application" %>

app/views/layouts/goals_index.html.erb
<% content_for :content do %>

	<article class="article">
		<div class="breadcrumb">
		  <%= link_to 'Dashboard', home_index_path %>
		  <%= link_to 'My Projects', projects_path %>
		   <%= link_to 'Project', project_goals_path(@project), class: "current-selection" %>
		</div>

		<h1 class="main-title">Project Details</h1>
		
		<div class="card project">
	    	<div class="card-image">
	        	<h3 class="card-image title"><%= @project.name %></h3> 
	        </div>

	        <div class="card-header">
	            <%= @project.type_is.capitalize %>
	        </div>

			<%= content_for?(:goals_index_content) ? yield(:goals_index_content) : yield %>



			<p>&nbsp;</p>
		</div>

	</article>

	<section class="stats">
		<div class="quotes">
			<h3>&ldquo;There is no greater agony than bearing an untold story inside you.&rdquo; </h3>
			<p>&ndash; Maya Angelou</p>
		</div>
	</section>
<% end %>

<%= render template: "layouts/application" %>

app/views/layouts/goals_new.html.erb
<% content_for :content do %>
	<article class="article">
		<div class="breadcrumb">
		  <%= link_to 'Dashboard', home_index_path %>
		  <%= link_to 'My Projects', projects_path %>
		  <%= link_to 'Project', project_goals_path(@project) %>
		  <a href="#" class="current-selection">Goal</a>
		</div>

		<h1 class="main-title">New Goal</h1>

		<div class="card project">
	    	<div class="card-image">
	        	<h3 class="card-image title"><%= link_to @project.name, project_goals_path(@project) %></h3> 
	        </div>
	        <div class="inner-project">
				<div class="card">
					<div class="card-image goal">
						<h6 class="goal"><%# @goal.type_is.capitalize %></h6> 
					</div>
					
					<%= content_for?(:goals_content) ? yield(:goals_content) : yield %>

				</div>
			</div>
		</div>
	</article>

	<section class="stats">
			<div class="quotes">
				<h3>“There is nothing to writing. All you do is sit down at a typewriter and bleed.” </h3>
				<p>&ndash; Ernest Hemingway</p>
			</div>
	</section>
<% end %>
<%= render template: "layouts/application" %>

app/views/layouts/projects_edit.html.erb
<% content_for :content do %>
	<article class="article">
		<div class="breadcrumb">
		  <%= link_to 'Dashboard', home_index_path %>
		  <%= link_to 'My Projects', projects_path %>
		   <%= link_to 'Project', project_goals_path(@project), class: "current-selection" %>
		</div>

		<h1 class="main-title">Edit project</h1>
		<div class="card project">
  			<div class="card-image">
      			
  		</div>

 

  		<div class="card-copy">
  

  			<%= content_for?(:projects_content) ? yield(:projects_content) : yield %>

		</div>
		</div>
	</article>
<% end %>

<%= render template: "layouts/application" %>